wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690014952.120418
    t:
      1:
      - 55
      - 86
      - 95
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      - 86
      - 92
      - 95
      3:
      - 23
      - 51
      4: 3.10.6
      5: 0.15.5
      8:
      - 5
      - 9
    framework: huggingface
