wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689553484.821911
    t:
      1:
      - 55
      - 86
      - 95
      2:
      - 55
      - 86
      - 95
      3:
      - 2
      - 23
      - 51
      4: 3.10.6
      5: 0.15.5
      8:
      - 5
