wandb_version: 1

doc_name:
  desc: null
  value: 10-K
wandb_project:
  desc: null
  value: llmapps
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689549968.719301
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      - 86
      - 92
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      - 86
      - 92
      3:
      - 2
      - 16
      - 23
      4: 3.10.6
      5: 0.15.5
      6: 4.30.2
      8:
      - 5
